# Generated by Django 2.2.7 on 2019-12-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_auto_20191201_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_visits',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
