# Generated by Django 2.2.7 on 2019-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_remove_post_count_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_visits',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
